; Adafruit Mini Sparkle Motion
;[env:adafruit_sparklemotionmini_esp32]
;extends = common:esp32
;board = adafruit_sparklemotionmini_esp32
;build_flags = -DARDUINO_SPARKLEMOTIONMINI_ESP32
;board_build.partitions = min_spiffs.csv
;board_build.filesystem = littlefs

[env:sparkle_motion_mini]
platform = espressif32
board = esp32dev
framework = arduino
board_build.mcu = esp32
board_build.f_cpu = 240000000L
monitor_speed = 115200
lib_deps =
    ;fastled/FastLED @ ^3.7.0
    adafruit/Adafruit NeoPixel @ ^1.12.0
upload_port = COM9
monitor_port = COM9

build_flags = 
	-D DEBUG_SCOMP_RX=0
	-D SCOMP_BAUD_RATE=115200
	-D PIN_SERIAL_RX=26
	-D PIN_SERIAL_TX=25
